baseURL = "/"
languageCode = "en-us"
title = "Pornhub Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "PornHub"
    subsite = "pornhub"
    description = "is the pornhub algorithm kidding with your perception of sex?"
    tagline = "Watch a tech-company fu*k your behavior data!"
  #  Some tech companies know you better than your partner ;)"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "More"
    weight = -110

 [[menu.featured]]
    name = "Algorithm Domination"
    url = "/submission"
    weight = -100
    pre = "/images/algorithmdom.svg"
    post = "Your data and what your master wants you to masturbate on today, tomorrow"
 [[menu.featured]]
    page = "compare"
    identifier = "compare"
    name = "Public Shame"
    url = "/compare"
    weight = -90
    pre = "/images/compare.svg"
    post = "Compare and measure your personalized recommandations and get a rough punishment"
 [[menu.featured]]
    page = "pov"
    identifier = "pov"
    name = "Behind the Scenes"
    url = "/pov"
    weight = -80
    pre = "/images/pov.svg"
    post = "See through our POV and play hard with our pleasure tools"

 [[menu.footer]]
    page = "Project analysis"
    identifier = "background"
    name = "Project analysis"
    url = "/project-analysis/"
    weight = 100
[[menu.footer]]
   page = "Tracking Exposed"
   identifier = "trex"
   name = "Umbrella project: Tracking Exposed"
   url = "https://tracking.exposed"
   weight = 90
