baseURL = "/"
languageCode = "en-us"
title = "Pornhub Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "PornHub"
    subsite = "pornhub"
    description = "is porn algorithm play with your perception of sex?"
    tagline = "How pornhub algorithm has an impact in the perception of sexuality?"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "THIS IS A WORK IN PROGRESS - DON'T RELEASE IT - DON'T USE IT"
    weight = -110

 [[menu.featured]]
    name = "API"
    url = "/research"
    weight = -100
    pre = "/images/yt-compare.jpg"
    post = "Personalized experiences demands personalized analysis"

 [[menu.featured]]
    page = "analysis"
    identifier = "analysis"
    name = "analysis"
    url = "/initial-analysis"
    weight = -90
    pre = "/images/yt-compare.jpg"
    post = "Initial analysis"

 [[menu.footer]]
    page = "Project analysis"
    identifier = "background"
    name = "Project analysis"
    url = "/API/"
    weight = 100
