baseURL = "/"
languageCode = "en-us"
title = "Pornhub Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "PornHub"
    subsite = "pornhub"
    description = "is porn algorithm kidding with your perception of sex?"
    tagline = "Some tech companies know you better than your partner..."

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "More"
    weight = -110

 [[menu.featured]]
    name = "submission"
    url = "/submission"
    weight = -100
    pre = "/images/yt-compare.jpg"
    post = "ALGORITHM DOMINATION What your master thinks you should masturbate on today"

 [[menu.featured]]
    page = "compare"
    identifier = "compare"
    name = "compare"
    url = "/compare"
    weight = -90
    pre = "/images/yt-compare.jpg"
    post = "PUBLIC SHAME Compare and measure your reccomandations and get punished"

 [[menu.featured]]
    page = "pov"
    identifier = "pov"
    name = "pov"
    url = "/pov"
    weight = -80
    pre = "/images/yt-compare.jpg"
    post = "BEHIND THE SCENES See through our POV and discover our tools"

 [[menu.footer]]
    page = "Project analysis"
    identifier = "background"
    name = "Project analysis"
    url = "/API/"
    weight = 100
